/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowParkingHome (void)
{
  GtkWidget *windowParkingHome;
  GtkWidget *fixed1;
  GtkWidget *treeviewParkingHome;
  GtkWidget *ParkingSearchTextField;
  GtkWidget *label1;
  GtkWidget *buttonAjouterParkingW;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *buttonModifierParkingW;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *buttonSupprimerParkingW;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *buttonActualiserParkingW;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *buttonStatistiqueParkingW;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image13;
  GtkWidget *label28;
  GtkWidget *buttonRechercheParking;
  GtkWidget *image7;
  GtkWidget *buttonFiltreParking;
  GtkWidget *image6;
  GtkWidget *buttonReturnMenuParking;
  GtkWidget *image8;
  GtkWidget *ParkingFiltreTextField;

  windowParkingHome = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowParkingHome), _("Gestion Parking"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowParkingHome), fixed1);
  gtk_widget_set_size_request (fixed1, 943, 810);

  treeviewParkingHome = gtk_tree_view_new ();
  gtk_widget_show (treeviewParkingHome);
  gtk_fixed_put (GTK_FIXED (fixed1), treeviewParkingHome, 96, 240);
  gtk_widget_set_size_request (treeviewParkingHome, 546, 376);

  ParkingSearchTextField = gtk_entry_new ();
  gtk_widget_show (ParkingSearchTextField);
  gtk_fixed_put (GTK_FIXED (fixed1), ParkingSearchTextField, 96, 176);
  gtk_widget_set_size_request (ParkingSearchTextField, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ParkingSearchTextField), 8226);

  label1 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">\nGestion Parking\n </span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 304, 72);
  gtk_widget_set_size_request (label1, 259, 50);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  buttonAjouterParkingW = gtk_button_new ();
  gtk_widget_show (buttonAjouterParkingW);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAjouterParkingW, 720, 184);
  gtk_widget_set_size_request (buttonAjouterParkingW, 158, 63);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonAjouterParkingW), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  buttonModifierParkingW = gtk_button_new ();
  gtk_widget_show (buttonModifierParkingW);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonModifierParkingW, 720, 288);
  gtk_widget_set_size_request (buttonModifierParkingW, 158, 63);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonModifierParkingW), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  buttonSupprimerParkingW = gtk_button_new ();
  gtk_widget_show (buttonSupprimerParkingW);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSupprimerParkingW, 720, 408);
  gtk_widget_set_size_request (buttonSupprimerParkingW, 158, 63);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonSupprimerParkingW), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  buttonActualiserParkingW = gtk_button_new ();
  gtk_widget_show (buttonActualiserParkingW);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonActualiserParkingW, 720, 520);
  gtk_widget_set_size_request (buttonActualiserParkingW, 158, 63);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonActualiserParkingW), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  buttonStatistiqueParkingW = gtk_button_new ();
  gtk_widget_show (buttonStatistiqueParkingW);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonStatistiqueParkingW, 720, 624);
  gtk_widget_set_size_request (buttonStatistiqueParkingW, 158, 63);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonStatistiqueParkingW), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image13 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox10), image13, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Affectation"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox10), label28, FALSE, FALSE, 0);

  buttonRechercheParking = gtk_button_new ();
  gtk_widget_show (buttonRechercheParking);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonRechercheParking, 280, 176);
  gtk_widget_set_size_request (buttonRechercheParking, 66, 29);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (buttonRechercheParking), image7);

  buttonFiltreParking = gtk_button_new ();
  gtk_widget_show (buttonFiltreParking);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonFiltreParking, 584, 176);
  gtk_widget_set_size_request (buttonFiltreParking, 66, 29);

  image6 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (buttonFiltreParking), image6);

  buttonReturnMenuParking = gtk_button_new ();
  gtk_widget_show (buttonReturnMenuParking);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonReturnMenuParking, 32, 32);
  gtk_widget_set_size_request (buttonReturnMenuParking, 66, 29);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (buttonReturnMenuParking), image8);

  ParkingFiltreTextField = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ParkingFiltreTextField);
  gtk_fixed_put (GTK_FIXED (fixed1), ParkingFiltreTextField, 384, 176);
  gtk_widget_set_size_request (ParkingFiltreTextField, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ParkingFiltreTextField), _("monastir"));

  g_signal_connect ((gpointer) treeviewParkingHome, "row_activated",
                    G_CALLBACK (on_treeviewParkingHome_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouterParkingW, "clicked",
                    G_CALLBACK (on_buttonAjouterParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifierParkingW, "clicked",
                    G_CALLBACK (on_buttonModifierParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimerParkingW, "clicked",
                    G_CALLBACK (on_buttonSupprimerParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonActualiserParkingW, "clicked",
                    G_CALLBACK (on_buttonActualiserParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonStatistiqueParkingW, "clicked",
                    G_CALLBACK (on_buttonStatistiqueParkingW_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercheParking, "clicked",
                    G_CALLBACK (on_buttonRechercheParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonFiltreParking, "clicked",
                    G_CALLBACK (on_buttonFiltreParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonReturnMenuParking, "clicked",
                    G_CALLBACK (on_buttonReturnMenuParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingHome, windowParkingHome, "windowParkingHome");
  GLADE_HOOKUP_OBJECT (windowParkingHome, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, treeviewParkingHome, "treeviewParkingHome");
  GLADE_HOOKUP_OBJECT (windowParkingHome, ParkingSearchTextField, "ParkingSearchTextField");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonAjouterParkingW, "buttonAjouterParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonModifierParkingW, "buttonModifierParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonSupprimerParkingW, "buttonSupprimerParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonActualiserParkingW, "buttonActualiserParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonStatistiqueParkingW, "buttonStatistiqueParkingW");
  GLADE_HOOKUP_OBJECT (windowParkingHome, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (windowParkingHome, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowParkingHome, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonRechercheParking, "buttonRechercheParking");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonFiltreParking, "buttonFiltreParking");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowParkingHome, buttonReturnMenuParking, "buttonReturnMenuParking");
  GLADE_HOOKUP_OBJECT (windowParkingHome, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowParkingHome, ParkingFiltreTextField, "ParkingFiltreTextField");

  return windowParkingHome;
}

GtkWidget*
create_windowParkingSup (void)
{
  GtkWidget *windowParkingSup;
  GtkWidget *fixed2;
  GtkWidget *textIdSupParking;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *textIdSupParkingControl;
  GtkWidget *btnSupParking;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label11;
  GtkWidget *btnCancelSupParking;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label10;

  windowParkingSup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowParkingSup), _("Supprimer Parking"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowParkingSup), fixed2);

  textIdSupParking = gtk_entry_new ();
  gtk_widget_show (textIdSupParking);
  gtk_fixed_put (GTK_FIXED (fixed2), textIdSupParking, 184, 72);
  gtk_widget_set_size_request (textIdSupParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textIdSupParking), 8226);

  label7 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 80, 80);
  gtk_widget_set_size_request (label7, 101, 17);

  label8 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Supprimer Parking </span>\n"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 120, 32);
  gtk_widget_set_size_request (label8, 240, 24);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  textIdSupParkingControl = gtk_label_new ("");
  gtk_widget_show (textIdSupParkingControl);
  gtk_fixed_put (GTK_FIXED (fixed2), textIdSupParkingControl, 96, 144);
  gtk_widget_set_size_request (textIdSupParkingControl, 332, 17);

  btnSupParking = gtk_button_new ();
  gtk_widget_show (btnSupParking);
  gtk_fixed_put (GTK_FIXED (fixed2), btnSupParking, 272, 184);
  gtk_widget_set_size_request (btnSupParking, 120, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btnSupParking), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox7), label11, FALSE, FALSE, 0);

  btnCancelSupParking = gtk_button_new ();
  gtk_widget_show (btnCancelSupParking);
  gtk_fixed_put (GTK_FIXED (fixed2), btnCancelSupParking, 120, 184);
  gtk_widget_set_size_request (btnCancelSupParking, 120, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btnCancelSupParking), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) btnSupParking, "clicked",
                    G_CALLBACK (on_btnSupParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnCancelSupParking, "clicked",
                    G_CALLBACK (on_btnCancelSupParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingSup, windowParkingSup, "windowParkingSup");
  GLADE_HOOKUP_OBJECT (windowParkingSup, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowParkingSup, textIdSupParking, "textIdSupParking");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label7, "label7");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label8, "label8");
  GLADE_HOOKUP_OBJECT (windowParkingSup, textIdSupParkingControl, "textIdSupParkingControl");
  GLADE_HOOKUP_OBJECT (windowParkingSup, btnSupParking, "btnSupParking");
  GLADE_HOOKUP_OBJECT (windowParkingSup, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowParkingSup, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowParkingSup, image10, "image10");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label11, "label11");
  GLADE_HOOKUP_OBJECT (windowParkingSup, btnCancelSupParking, "btnCancelSupParking");
  GLADE_HOOKUP_OBJECT (windowParkingSup, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowParkingSup, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowParkingSup, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowParkingSup, label10, "label10");

  return windowParkingSup;
}

GtkWidget*
create_windowParkingAjout (void)
{
  GtkWidget *windowParkingAjout;
  GtkWidget *fixed3;
  GtkWidget *textIdAjoutParking;
  GtkWidget *label12;
  GtkObject *spinCapaciteAjoutParking_adj;
  GtkWidget *spinCapaciteAjoutParking;
  GtkWidget *label17;
  GtkWidget *textNomAjoutParking;
  GtkObject *spinTarifAjoutParking_adj;
  GtkWidget *spinTarifAjoutParking;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label29;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *label18;
  GtkWidget *btnAjoutParking;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label25;
  GtkWidget *btnCancelAjoutParking;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label26;
  GtkWidget *windowParkingAjoutControl;
  GtkWidget *checkSecNonAjoutParking;
  GtkWidget *checkSecOuiAjoutParking;
  GtkWidget *radioHoraireAjoutParking;
  GSList *radioHoraireAjoutParking_group = NULL;
  GtkWidget *radioJournalierAjoutParking;
  GtkWidget *comboAdresseAjoutParking;

  windowParkingAjout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowParkingAjout, 800, 731);
  gtk_window_set_title (GTK_WINDOW (windowParkingAjout), _("Ajouter Parking"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowParkingAjout), fixed3);

  textIdAjoutParking = gtk_entry_new ();
  gtk_widget_show (textIdAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), textIdAjoutParking, 344, 128);
  gtk_widget_set_size_request (textIdAjoutParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textIdAjoutParking), 8226);

  label12 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 216, 136);
  gtk_widget_set_size_request (label12, 103, 17);

  spinCapaciteAjoutParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinCapaciteAjoutParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinCapaciteAjoutParking_adj), 1, 0);
  gtk_widget_show (spinCapaciteAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), spinCapaciteAjoutParking, 400, 312);
  gtk_widget_set_size_request (spinCapaciteAjoutParking, 60, 27);

  label17 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Ajouter Parking</span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 312, 40);
  gtk_widget_set_size_request (label17, 217, 32);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  textNomAjoutParking = gtk_entry_new ();
  gtk_widget_show (textNomAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), textNomAjoutParking, 344, 184);
  gtk_widget_set_size_request (textNomAjoutParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textNomAjoutParking), 8226);

  spinTarifAjoutParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinTarifAjoutParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinTarifAjoutParking_adj), 1, 0);
  gtk_widget_show (spinTarifAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), spinTarifAjoutParking, 400, 376);
  gtk_widget_set_size_request (spinTarifAjoutParking, 60, 27);

  label23 = gtk_label_new (_("Type tarifaire"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed3), label23, 144, 456);
  gtk_widget_set_size_request (label23, 168, 17);

  label24 = gtk_label_new (_("Securit\303\251 disponible"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed3), label24, 152, 504);
  gtk_widget_set_size_request (label24, 168, 17);

  label29 = gtk_label_new (_("Tarif"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed3), label29, 184, 384);
  gtk_widget_set_size_request (label29, 177, 17);

  label19 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 240, 248);
  gtk_widget_set_size_request (label19, 66, 17);

  label21 = gtk_label_new (_("Capacit\303\251"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 192, 320);
  gtk_widget_set_size_request (label21, 177, 17);

  label18 = gtk_label_new (_("nom"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 240, 192);
  gtk_widget_set_size_request (label18, 62, 17);

  btnAjoutParking = gtk_button_new ();
  gtk_widget_show (btnAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), btnAjoutParking, 464, 664);
  gtk_widget_set_size_request (btnAjoutParking, 168, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (btnAjoutParking), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox8), label25, FALSE, FALSE, 0);

  btnCancelAjoutParking = gtk_button_new ();
  gtk_widget_show (btnCancelAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), btnCancelAjoutParking, 224, 664);
  gtk_widget_set_size_request (btnCancelAjoutParking, 168, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (btnCancelAjoutParking), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);

  windowParkingAjoutControl = gtk_label_new ("");
  gtk_widget_show (windowParkingAjoutControl);
  gtk_fixed_put (GTK_FIXED (fixed3), windowParkingAjoutControl, 216, 600);
  gtk_widget_set_size_request (windowParkingAjoutControl, 473, 17);

  checkSecNonAjoutParking = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkSecNonAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), checkSecNonAjoutParking, 512, 496);
  gtk_widget_set_size_request (checkSecNonAjoutParking, 118, 24);

  checkSecOuiAjoutParking = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkSecOuiAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), checkSecOuiAjoutParking, 328, 496);
  gtk_widget_set_size_request (checkSecOuiAjoutParking, 118, 24);

  radioHoraireAjoutParking = gtk_radio_button_new_with_mnemonic (NULL, _("Horaire"));
  gtk_widget_show (radioHoraireAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), radioHoraireAjoutParking, 328, 456);
  gtk_widget_set_size_request (radioHoraireAjoutParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHoraireAjoutParking), radioHoraireAjoutParking_group);
  radioHoraireAjoutParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHoraireAjoutParking));

  radioJournalierAjoutParking = gtk_radio_button_new_with_mnemonic (NULL, _("journalier"));
  gtk_widget_show (radioJournalierAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), radioJournalierAjoutParking, 520, 456);
  gtk_widget_set_size_request (radioJournalierAjoutParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJournalierAjoutParking), radioHoraireAjoutParking_group);
  radioHoraireAjoutParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJournalierAjoutParking));

  comboAdresseAjoutParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboAdresseAjoutParking);
  gtk_fixed_put (GTK_FIXED (fixed3), comboAdresseAjoutParking, 344, 240);
  gtk_widget_set_size_request (comboAdresseAjoutParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseAjoutParking), _("monastir"));

  g_signal_connect ((gpointer) btnAjoutParking, "clicked",
                    G_CALLBACK (on_btnAjoutParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnCancelAjoutParking, "clicked",
                    G_CALLBACK (on_btnCancelAjoutParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkSecNonAjoutParking, "toggled",
                    G_CALLBACK (on_checkSecNonAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkSecOuiAjoutParking, "toggled",
                    G_CALLBACK (on_checkSecOuiAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioHoraireAjoutParking, "toggled",
                    G_CALLBACK (on_radioHoraireAjoutParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJournalierAjoutParking, "toggled",
                    G_CALLBACK (on_radioJournalierAjoutParking_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingAjout, windowParkingAjout, "windowParkingAjout");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, textIdAjoutParking, "textIdAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label12, "label12");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, spinCapaciteAjoutParking, "spinCapaciteAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, textNomAjoutParking, "textNomAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, spinTarifAjoutParking, "spinTarifAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label23, "label23");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label24, "label24");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label19, "label19");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label21, "label21");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label18, "label18");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, btnAjoutParking, "btnAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, image11, "image11");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label25, "label25");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, btnCancelAjoutParking, "btnCancelAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, label26, "label26");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, windowParkingAjoutControl, "windowParkingAjoutControl");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, checkSecNonAjoutParking, "checkSecNonAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, checkSecOuiAjoutParking, "checkSecOuiAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, radioHoraireAjoutParking, "radioHoraireAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, radioJournalierAjoutParking, "radioJournalierAjoutParking");
  GLADE_HOOKUP_OBJECT (windowParkingAjout, comboAdresseAjoutParking, "comboAdresseAjoutParking");

  return windowParkingAjout;
}

GtkWidget*
create_windowParkingModif (void)
{
  GtkWidget *windowParkingModif;
  GtkWidget *fixed4;
  GtkWidget *textIdModifParking;
  GtkWidget *label30;
  GtkObject *spinCapaciteModifParking_adj;
  GtkWidget *spinCapaciteModifParking;
  GtkWidget *textNomModifParking;
  GtkObject *spinTarifModifParking_adj;
  GtkWidget *spinTarifModifParking;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label31;
  GtkWidget *buttonParkinghercheRecModif;
  GtkWidget *image17;
  GtkWidget *comboAdresseModifParking;
  GtkWidget *checkSecNonModifParking;
  GtkWidget *checkSecOuiModifParking;
  GtkWidget *radioHoraireModifParking;
  GSList *radioHoraireModifParking_group = NULL;
  GtkWidget *radioJournalierModifParking;
  GtkWidget *btnModifParking;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label41;
  GtkWidget *btnCancelModifParking;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image15;
  GtkWidget *label39;
  GtkWidget *windowParkingModifControl;

  windowParkingModif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (windowParkingModif, 800, 731);
  gtk_window_set_title (GTK_WINDOW (windowParkingModif), _("Modifier Parking"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowParkingModif), fixed4);

  textIdModifParking = gtk_entry_new ();
  gtk_widget_show (textIdModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), textIdModifParking, 344, 128);
  gtk_widget_set_size_request (textIdModifParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textIdModifParking), 8226);

  label30 = gtk_label_new (_("identifiant"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 216, 136);
  gtk_widget_set_size_request (label30, 103, 17);

  spinCapaciteModifParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinCapaciteModifParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinCapaciteModifParking_adj), 1, 0);
  gtk_widget_show (spinCapaciteModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), spinCapaciteModifParking, 400, 312);
  gtk_widget_set_size_request (spinCapaciteModifParking, 60, 27);

  textNomModifParking = gtk_entry_new ();
  gtk_widget_show (textNomModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), textNomModifParking, 344, 184);
  gtk_widget_set_size_request (textNomModifParking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (textNomModifParking), 8226);

  spinTarifModifParking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinTarifModifParking = gtk_spin_button_new (GTK_ADJUSTMENT (spinTarifModifParking_adj), 1, 0);
  gtk_widget_show (spinTarifModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), spinTarifModifParking, 400, 376);
  gtk_widget_set_size_request (spinTarifModifParking, 60, 27);

  label32 = gtk_label_new (_("Type tarifaire"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 144, 456);
  gtk_widget_set_size_request (label32, 168, 17);

  label33 = gtk_label_new (_("Securit\303\251 disponible"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 152, 504);
  gtk_widget_set_size_request (label33, 168, 17);

  label34 = gtk_label_new (_("Tarif"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 184, 384);
  gtk_widget_set_size_request (label34, 177, 17);

  label35 = gtk_label_new (_("Adresse"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 240, 248);
  gtk_widget_set_size_request (label35, 66, 17);

  label36 = gtk_label_new (_("Capacit\303\251"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 192, 320);
  gtk_widget_set_size_request (label36, 177, 17);

  label37 = gtk_label_new (_("nom"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 240, 192);
  gtk_widget_set_size_request (label37, 62, 17);

  label31 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">Modifier Parking</span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 312, 40);
  gtk_widget_set_size_request (label31, 217, 32);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  buttonParkinghercheRecModif = gtk_button_new ();
  gtk_widget_show (buttonParkinghercheRecModif);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonParkinghercheRecModif, 544, 128);
  gtk_widget_set_size_request (buttonParkinghercheRecModif, 74, 29);

  image17 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (buttonParkinghercheRecModif), image17);

  comboAdresseModifParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboAdresseModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), comboAdresseModifParking, 344, 240);
  gtk_widget_set_size_request (comboAdresseModifParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("bizerte"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboAdresseModifParking), _("monastir"));

  checkSecNonModifParking = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkSecNonModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), checkSecNonModifParking, 552, 496);
  gtk_widget_set_size_request (checkSecNonModifParking, 118, 24);

  checkSecOuiModifParking = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkSecOuiModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), checkSecOuiModifParking, 352, 496);
  gtk_widget_set_size_request (checkSecOuiModifParking, 118, 24);

  radioHoraireModifParking = gtk_radio_button_new_with_mnemonic (NULL, _("Horaire"));
  gtk_widget_show (radioHoraireModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), radioHoraireModifParking, 352, 456);
  gtk_widget_set_size_request (radioHoraireModifParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHoraireModifParking), radioHoraireModifParking_group);
  radioHoraireModifParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHoraireModifParking));

  radioJournalierModifParking = gtk_radio_button_new_with_mnemonic (NULL, _("journalier"));
  gtk_widget_show (radioJournalierModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), radioJournalierModifParking, 552, 456);
  gtk_widget_set_size_request (radioJournalierModifParking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJournalierModifParking), radioHoraireModifParking_group);
  radioHoraireModifParking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJournalierModifParking));

  btnModifParking = gtk_button_new ();
  gtk_widget_show (btnModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), btnModifParking, 464, 664);
  gtk_widget_set_size_request (btnModifParking, 168, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (btnModifParking), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, FALSE, FALSE, 0);

  btnCancelModifParking = gtk_button_new ();
  gtk_widget_show (btnCancelModifParking);
  gtk_fixed_put (GTK_FIXED (fixed4), btnCancelModifParking, 224, 664);
  gtk_widget_set_size_request (btnCancelModifParking, 168, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (btnCancelModifParking), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image15 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox12), image15, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox12), label39, FALSE, FALSE, 0);

  windowParkingModifControl = gtk_label_new ("");
  gtk_widget_show (windowParkingModifControl);
  gtk_fixed_put (GTK_FIXED (fixed4), windowParkingModifControl, 216, 600);
  gtk_widget_set_size_request (windowParkingModifControl, 473, 17);

  g_signal_connect ((gpointer) buttonParkinghercheRecModif, "clicked",
                    G_CALLBACK (on_buttonParkinghercheRecModif_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkSecNonModifParking, "toggled",
                    G_CALLBACK (on_checkSecNonModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkSecOuiModifParking, "toggled",
                    G_CALLBACK (on_checkSecOuiModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioHoraireModifParking, "toggled",
                    G_CALLBACK (on_radioHoraireModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJournalierModifParking, "toggled",
                    G_CALLBACK (on_radioJournalierModifParking_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnModifParking, "clicked",
                    G_CALLBACK (on_btnModifParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnCancelModifParking, "clicked",
                    G_CALLBACK (on_btnCancelModifParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingModif, windowParkingModif, "windowParkingModif");
  GLADE_HOOKUP_OBJECT (windowParkingModif, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowParkingModif, textIdModifParking, "textIdModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowParkingModif, spinCapaciteModifParking, "spinCapaciteModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, textNomModifParking, "textNomModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, spinTarifModifParking, "spinTarifModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label32, "label32");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label33, "label33");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label34, "label34");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label37, "label37");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowParkingModif, buttonParkinghercheRecModif, "buttonParkinghercheRecModif");
  GLADE_HOOKUP_OBJECT (windowParkingModif, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowParkingModif, comboAdresseModifParking, "comboAdresseModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, checkSecNonModifParking, "checkSecNonModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, checkSecOuiModifParking, "checkSecOuiModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, radioHoraireModifParking, "radioHoraireModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, radioJournalierModifParking, "radioJournalierModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, btnModifParking, "btnModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowParkingModif, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowParkingModif, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label41, "label41");
  GLADE_HOOKUP_OBJECT (windowParkingModif, btnCancelModifParking, "btnCancelModifParking");
  GLADE_HOOKUP_OBJECT (windowParkingModif, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowParkingModif, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowParkingModif, image15, "image15");
  GLADE_HOOKUP_OBJECT (windowParkingModif, label39, "label39");
  GLADE_HOOKUP_OBJECT (windowParkingModif, windowParkingModifControl, "windowParkingModifControl");

  return windowParkingModif;
}

GtkWidget*
create_windowParkingAffectation (void)
{
  GtkWidget *windowParkingAffectation;
  GtkWidget *fixed5;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *btnAffectationParking;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image18;
  GtkWidget *label44;
  GtkWidget *btnCancelAffectationParking;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label45;
  GtkWidget *textIdAffectationParkingControl;
  GtkWidget *label47;
  GtkWidget *comboIdAgentAffectParking;
  GtkWidget *comboIdParkingAffectParking;

  windowParkingAffectation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowParkingAffectation), _("Affectaion Agent Parking"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (windowParkingAffectation), fixed5);
  gtk_widget_set_size_request (fixed5, 675, 520);

  label42 = gtk_label_new (_("Identifant parking"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed5), label42, 64, 136);
  gtk_widget_set_size_request (label42, 177, 17);

  label43 = gtk_label_new (_("identifiant Agent"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed5), label43, 96, 224);
  gtk_widget_set_size_request (label43, 142, 17);

  btnAffectationParking = gtk_button_new ();
  gtk_widget_show (btnAffectationParking);
  gtk_fixed_put (GTK_FIXED (fixed5), btnAffectationParking, 64, 344);
  gtk_widget_set_size_request (btnAffectationParking, 192, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btnAffectationParking), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox14), image18, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  btnCancelAffectationParking = gtk_button_new ();
  gtk_widget_show (btnCancelAffectationParking);
  gtk_fixed_put (GTK_FIXED (fixed5), btnCancelAffectationParking, 64, 400);
  gtk_widget_set_size_request (btnCancelAffectationParking, 192, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btnCancelAffectationParking), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox15), label45, FALSE, FALSE, 0);

  textIdAffectationParkingControl = gtk_label_new ("");
  gtk_widget_show (textIdAffectationParkingControl);
  gtk_fixed_put (GTK_FIXED (fixed5), textIdAffectationParkingControl, 152, 288);
  gtk_widget_set_size_request (textIdAffectationParkingControl, 391, 17);

  label47 = gtk_label_new (_("<span foreground=\"red\" weight=\"bold\">\nAffecter Agent Parking</span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed5), label47, 224, 24);
  gtk_widget_set_size_request (label47, 243, 67);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  comboIdAgentAffectParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboIdAgentAffectParking);
  gtk_fixed_put (GTK_FIXED (fixed5), comboIdAgentAffectParking, 248, 216);
  gtk_widget_set_size_request (comboIdAgentAffectParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN123456"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN789012"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN345678"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN901234"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdAgentAffectParking), _("CIN567890"));

  comboIdParkingAffectParking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboIdParkingAffectParking);
  gtk_fixed_put (GTK_FIXED (fixed5), comboIdParkingAffectParking, 248, 128);
  gtk_widget_set_size_request (comboIdParkingAffectParking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboIdParkingAffectParking), _("6"));

  g_signal_connect ((gpointer) btnAffectationParking, "clicked",
                    G_CALLBACK (on_btnAffectationParking_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnCancelAffectationParking, "clicked",
                    G_CALLBACK (on_btnCancelAffectationParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowParkingAffectation, windowParkingAffectation, "windowParkingAffectation");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label42, "label42");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, btnAffectationParking, "btnAffectationParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, btnCancelAffectationParking, "btnCancelAffectationParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, image19, "image19");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label45, "label45");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, textIdAffectationParkingControl, "textIdAffectationParkingControl");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, label47, "label47");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, comboIdAgentAffectParking, "comboIdAgentAffectParking");
  GLADE_HOOKUP_OBJECT (windowParkingAffectation, comboIdParkingAffectParking, "comboIdParkingAffectParking");

  return windowParkingAffectation;
}

