/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowParkingHome (void);
GtkWidget* create_windowParkingSup (void);
GtkWidget* create_windowParkingAjout (void);
GtkWidget* create_windowParkingModif (void);
GtkWidget* create_windowParkingAffectation (void);
